# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'amorous'

google-ID: 'UA-146421430-1'

menu:
- {name: 'Try it out', folder: 'pages', file: 'try.html'}
- {name: 'Products', folder: 'pages', file: 'products.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

social:
- {icon: 'envelope', link: 'mailto:duerr.sebastian@gmail.com'}

sharing_button_prompt: '                          .'
