# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'amorous'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-146421430-1'

menu:
- {name: 'Try it!', folder: 'pages', file: 'try.html'}
- {name: 'Read more', folder: 'pages', file: 'stay-tuned.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:'}

sharing_button_prompt: 'Please share to spread amorous texts!'
